//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EkilibrateUI.Areas.SitioAdministrativo.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoricoUsuarioPorRol
    {
        public int IdUsuario { get; set; }
        public int IdRol { get; set; }
        public System.DateTime TransacDateTime { get; set; }
        public string TransacUser { get; set; }
        public System.DateTime HistoricTransacDateTime { get; set; }
        public string HistoricTransacUser { get; set; }
    }
}
