//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EkilibrateUI.Areas.SitioAdministrativo.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParametroGeneral
    {
        public int IdParametroGeneral { get; set; }
        public string Nombre { get; set; }
        public string Valor { get; set; }
        public Nullable<int> IdParametroTipo { get; set; }
        public bool Activo { get; set; }
        public int IdPropietario { get; set; }
        public System.DateTime TransacDateTime { get; set; }
        public string TransacUser { get; set; }
    
        public virtual Propietario Propietario { get; set; }
        public virtual ParametroTipo ParametroTipo { get; set; }
    }
}
