//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EkilibrateUI.Areas.SitioAdministrativo.Models.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EkiibrateDBEntities : DbContext
    {
        public EkiibrateDBEntities()
            : base("name=EkiibrateDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Menu> Menu { get; set; }
        public virtual DbSet<MenuTipo> MenuTipo { get; set; }
        public virtual DbSet<Objeto> Objeto { get; set; }
        public virtual DbSet<ParametroGeneral> ParametroGeneral { get; set; }
        public virtual DbSet<ParametroTipo> ParametroTipo { get; set; }
        public virtual DbSet<Permiso> Permiso { get; set; }
        public virtual DbSet<Producto> Producto { get; set; }
        public virtual DbSet<Propietario> Propietario { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<UsuarioPorRol> UsuarioPorRol { get; set; }
        public virtual DbSet<HistoricoUsuarioPorRol> HistoricoUsuarioPorRol { get; set; }
        public virtual DbSet<GE_Persona> GE_Persona { get; set; }
        public virtual DbSet<TipoUsuario> TipoUsuario { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    
        public virtual int SP_PermisoAObjeto_Del(Nullable<int> idObjeto, Nullable<int> idRol, string userTransac)
        {
            var idObjetoParameter = idObjeto.HasValue ?
                new ObjectParameter("IdObjeto", idObjeto) :
                new ObjectParameter("IdObjeto", typeof(int));
    
            var idRolParameter = idRol.HasValue ?
                new ObjectParameter("IdRol", idRol) :
                new ObjectParameter("IdRol", typeof(int));
    
            var userTransacParameter = userTransac != null ?
                new ObjectParameter("UserTransac", userTransac) :
                new ObjectParameter("UserTransac", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_PermisoAObjeto_Del", idObjetoParameter, idRolParameter, userTransacParameter);
        }
    
        public virtual int SP_PermisoAObjeto_Ins(Nullable<int> idObjeto, Nullable<int> idRol, string userTransac)
        {
            var idObjetoParameter = idObjeto.HasValue ?
                new ObjectParameter("IdObjeto", idObjeto) :
                new ObjectParameter("IdObjeto", typeof(int));
    
            var idRolParameter = idRol.HasValue ?
                new ObjectParameter("IdRol", idRol) :
                new ObjectParameter("IdRol", typeof(int));
    
            var userTransacParameter = userTransac != null ?
                new ObjectParameter("UserTransac", userTransac) :
                new ObjectParameter("UserTransac", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_PermisoAObjeto_Ins", idObjetoParameter, idRolParameter, userTransacParameter);
        }
    }
}
