//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarcoSoftUtilidades.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permiso
    {
        public int IdRol { get; set; }
        public int IdObjeto { get; set; }
        public System.DateTime TransacDateTime { get; set; }
        public string TransacUser { get; set; }
    
        public virtual Objeto Objeto { get; set; }
        public virtual Rol Rol { get; set; }
    }
}
