CREATE TABLE [dbo].[PAR.CONDICION](
	[ID_CONDICION] [numeric](18, 0) NOT NULL,
	[NOMBRE_CONDICION] [varchar](max) NULL,
 CONSTRAINT [PK_PAR_CONDICION] PRIMARY KEY CLUSTERED 
(
	[ID_CONDICION] ASC
)
) 