CREATE TABLE [dbo].[PAR.MEDIDA_BEBIDA](
	[ID_PARTICIPANTE] [numeric](18, 0) NOT NULL,
	[ID_MEDIDA] [numeric](18, 0) NOT NULL,
	[RESPUESTA] [bit] NULL,
	CONSTRAINT [FK_PAR_MEDIDA_BEBIDA_PAR_INFORMACION_GENERAL] FOREIGN KEY ([ID_PARTICIPANTE]) REFERENCES [PAR.INFORMACION_GENERAL]([ID_PARTICIPANTE]),
	CONSTRAINT [FK_PAR_MEDIDA_BEBIDA_PAR_MEDIDA] FOREIGN KEY ([ID_MEDIDA]) REFERENCES [PAR.MEDIDA]([ID_MEDIDA]),
	PRIMARY KEY ([ID_PARTICIPANTE], [ID_MEDIDA])
)