CREATE TABLE [dbo].[PAR.ENFERMEDAD](
	[ID_PARTICIPANTE] [numeric](18, 0) NOT NULL,
	[ID_ENFERMEDAD] [numeric](18, 0) NOT NULL,
	[RESPUESTA] [bit] NULL,
	CONSTRAINT [FK_PAR_ENFERMEDAD_PAR_INFORMACION_GENERAL] FOREIGN KEY ([ID_PARTICIPANTE]) REFERENCES [PAR.INFORMACION_GENERAL]([ID_PARTICIPANTE]),
	CONSTRAINT [FK_PAR_ENFERMEDAD_PAR_TIPO_ENFERMEDAD] FOREIGN KEY ([ID_ENFERMEDAD]) REFERENCES [PAR.TIPO_ENFERMEDAD]([ID_ENFERMEDAD]),
	PRIMARY KEY ([ID_PARTICIPANTE], [ID_ENFERMEDAD]) 
)