CREATE TABLE [dbo].[PAR.COMUNICACION_ASERTIVA_UNO](
	[ID_PARTICIPANTE] [numeric](18, 0) NOT NULL,
	[ID_PREGUNTA] [numeric](18, 0) NOT NULL,
	[EN_ABSOLUTO] [bit] NULL,
	[UN_POCO] [bit] NULL,
	[BASTANTE] [bit] NULL,
	[MUCHO] [bit] NULL,
	[MUCHISIMO] [bit] NULL,
	CONSTRAINT [FK_PAR_COMUNICACION_ASERTIVA_UNO_PAR_INFORMACION_GENERAL] FOREIGN KEY ([ID_PARTICIPANTE]) REFERENCES [PAR.INFORMACION_GENERAL]([ID_PARTICIPANTE]),
	CONSTRAINT [FK_PAR_COMUNICACION_ASERTIVA_UNO_PAR_PREGUNTA_COMUNICACION_ASERTIVA_UNO] FOREIGN KEY ([ID_PREGUNTA]) REFERENCES [PAR.PREGUNTA_COMUNICACION_ASERTIVA_DOS]([ID_PREGUNTA]),
	PRIMARY KEY ([ID_PARTICIPANTE], [ID_PREGUNTA])
)