CREATE TABLE [dbo].[PAR.PREGUNTA_COMUNICACION_ASERTIVA_UNO](
	[ID_PREGUNTA] [numeric](18, 0) NOT NULL,
	[PREGUNTA] [varchar](MAX) NULL,
 CONSTRAINT [PK_PAR_PREGUNTA_COMUNICACION_ASERTIVA_UNO] PRIMARY KEY CLUSTERED 
(
	[ID_PREGUNTA] ASC
)
)