CREATE TABLE [dbo].[PAR.PREGUNTA_TIEMPO](
	[ID_PREGUNTA] [numeric](18, 0) NOT NULL,
	[PREGUNTA] [varchar](max) NOT NULL,
	[PesoSiempre] SMALLINT NOT NULL DEFAULT 0, 
	[PesoFrecuentemente] SMALLINT NOT NULL DEFAULT 0,
	[PesoCasiNunca] SMALLINT NOT NULL DEFAULT 0,
	[PesoNunca] SMALLINT NOT NULL DEFAULT 0,
 CONSTRAINT [PK_PAR_PREGUNTA_TIEMPO] PRIMARY KEY CLUSTERED 
(
	[ID_PREGUNTA] ASC
)
) 