CREATE TABLE [dbo].[PAR.FAC_RIESGO](
	[ID_PARTICIPANTE] [numeric](18, 0) NOT NULL,
	[FUMAR] [bit] NOT NULL,
	[CODIGO_FRECUENCIA_FUMAR] INT NULL,
	[NUM_CIGARROS] [numeric](18, 0) NOT NULL,
	[BEBER] [bit] NOT NULL,
	[CODIGO_FRECUENTE_BEBER] INT NULL,
	[NUMERO_BEBIDA] [numeric](18, 0) NULL,
	CONSTRAINT [PK_PAR.FAC_RIESGO] PRIMARY KEY ([ID_PARTICIPANTE])
)