CREATE TABLE [dbo].[PAR.ACTIVIDAD_FISICA](
	[ID_PARTICIPANTE] [numeric](18, 0) NOT NULL,
	[REALIZA_ACTIVIDAD] [bit] NOT NULL,
	[ID_PRINCIPAL] [numeric](18, 0) NULL,
	[PRINCIPAL_VECES] [numeric](18, 0) NULL,
	[PRINCIPAL_TIEMPO] [numeric](18, 0) NULL,
	[ID_SECUNDARIO] [numeric](18, 0) NULL,
	[SECUNDARIO_VECES] [numeric](18, 0) NULL,
	[SECUNDARIO_TIEMPO] [numeric](18, 0) NULL,
	[FACTOR_ACTIVIDAD] [DECIMAL](18,2) NULL, 
    CONSTRAINT [PK_PAR.ACTIVIDAD_FISICA] PRIMARY KEY ([ID_PARTICIPANTE]),
	CONSTRAINT [FK_PAR_ACTIVIDAD_PRINCIPAL_PAR_TIPO_EJERCICIO] FOREIGN KEY ([ID_PRINCIPAL]) REFERENCES [PAR.TIPO_EJERCICIO]([ID_EJERCICIO]),
	CONSTRAINT [FK_PAR_ACTIVIDAD_SECUNDARIA_PAR_TIPO_EJERCICIO] FOREIGN KEY ([ID_SECUNDARIO]) REFERENCES [PAR.TIPO_EJERCICIO]([ID_EJERCICIO])
)