CREATE TABLE [dbo].[PAR.COMUNICACION_ASERVITA_DOS](
	[ID_PARTICIPANTE] [numeric](18, 0) NOT NULL,
	[ID_PREGUNTA] [numeric](18, 0) NOT NULL,
	[SIEMPRE_LO_HAGO] [bit] NULL,
	[HABITUALMENTEBIT] [bit] NULL,
	[MITAD_VECES] [bit] NULL,
	[RARAMENTE] [bit] NULL,
	[NUNCA] [bit] NULL,
	CONSTRAINT [FK_PAR_COMUNICACION_ASERVITA_DOS_PAR_INFORMACION_GENERAL] FOREIGN KEY ([ID_PARTICIPANTE]) REFERENCES [PAR.INFORMACION_GENERAL]([ID_PARTICIPANTE]),
	CONSTRAINT [FK_PAR_COMUNICACION_ASERVITA_DOS_PAR_PREGUNTA_COMUNICACION_ASERTIVA_DOS] FOREIGN KEY ([ID_PREGUNTA]) REFERENCES [PAR.PREGUNTA_COMUNICACION_ASERTIVA_DOS]([ID_PREGUNTA]),
	PRIMARY KEY ([ID_PARTICIPANTE], [ID_PREGUNTA])
)