CREATE TABLE [dbo].[PAR.MEDIO_COMUNICACION](
	[ID_MEDIO_COMUNICACION] [numeric](18, 0) NOT NULL,
	[NOMBRE_MEDIO] [varchar](50) NOT NULL,
 CONSTRAINT [PK_PAR_MEDIO_COMUNICACION] PRIMARY KEY CLUSTERED 
(
	[ID_MEDIO_COMUNICACION] ASC
)
) 