CREATE TABLE [dbo].[PAR.RESP_ANSIEDAD](
	[ID_ANSIEDAD] [numeric](18, 0) NOT NULL,
	[ANSIEDAD] [varchar](max) NULL,
	[PESO] INT NOT NULL DEFAULT 0,
 CONSTRAINT [PK_PAR_RESP_ANSIEDAD] PRIMARY KEY CLUSTERED 
(
	[ID_ANSIEDAD] ASC
) 
) 