CREATE TABLE [dbo].[PAR.PREGUNTA_COMUNICACION_ASERTIVA_DOS](
	[ID_PREGUNTA] [numeric](18, 0) NOT NULL,
	[PREGUNTA] [varchar](max) NULL,
 CONSTRAINT [PK_PAR_PREGUNTA_COMUNICACION_ASERTIVA_DOS] PRIMARY KEY CLUSTERED 
(
	[ID_PREGUNTA] ASC
)
) 