CREATE TABLE [dbo].[PAR.ALIMENTACION_VASOS](
	[ID_VASOS] [numeric](18, 0) NOT NULL,
	[CLASIFICACION_VASOS] [varchar](50) NOT NULL,
 CONSTRAINT [PK_PAR_ALIMENTACION_VASOS] PRIMARY KEY ([ID_VASOS])) 