CREATE TABLE [dbo].[PAR.TIPO_EJERCICIO](
	[ID_EJERCICIO] [numeric](18, 0) NOT NULL,
	[NOMBRE_EJERCICIO] [varchar](150) NOT NULL,
	[CALORIAS_PM70] int NOT NULL,
	[CALORIAS_PH] [numeric](6, 2) NOT NULL,
	[CALORIAS_PM] [numeric](6, 2) NOT NULL,
 CONSTRAINT [PK_PAR_TIPO_EJERCICIO] PRIMARY KEY CLUSTERED 
(
	[ID_EJERCICIO] ASC
) 
) 