//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitioAdministrativoUI.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public int IdMenu { get; set; }
        public string Nombre { get; set; }
        public string ImageUrl { get; set; }
        public string Target { get; set; }
        public string TargetController { get; set; }
        public int IdObjeto { get; set; }
        public int IdMenuTipo { get; set; }
        public bool Activo { get; set; }
    
        public virtual MenuTipo MenuTipo { get; set; }
        public virtual Objeto Objeto { get; set; }
    }
}
