//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitioAdministrativoUI.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Objeto
    {
        public Objeto()
        {
            this.Menu = new HashSet<Menu>();
            this.Permiso = new HashSet<Permiso>();
            this.Objeto1 = new HashSet<Objeto>();
        }
    
        public int IdObjeto { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public int IdProducto { get; set; }
        public Nullable<int> IdObjetoPadre { get; set; }
        public bool Activo { get; set; }
    
        public virtual ICollection<Menu> Menu { get; set; }
        public virtual ICollection<Permiso> Permiso { get; set; }
        public virtual ICollection<Objeto> Objeto1 { get; set; }
        public virtual Objeto Objeto2 { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
