//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarcoSoftUtilidades.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADM_Contacto
    {
        public int EmpresaId { get; set; }
        public int PersonaId { get; set; }
        public bool EsPrincipal { get; set; }
    
        public virtual ADM_Empresa ADM_Empresa { get; set; }
        public virtual GE_Persona GE_Persona { get; set; }
    }
}
