//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarcoSoftUtilidades.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADM_Colaborador
    {
        public ADM_Colaborador()
        {
            this.PR_Nutricionista = new HashSet<PR_Nutricionista>();
        }
    
        public int Id { get; set; }
        public bool Nutricionista { get; set; }
        public bool Facilitador { get; set; }
        public bool Asistente { get; set; }
        public bool Enfermero_a_ { get; set; }
        public string Estado { get; set; }
    
        public virtual ICollection<PR_Nutricionista> PR_Nutricionista { get; set; }
        public virtual GE_Persona GE_Persona { get; set; }
    }
}
