//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarcoSoftUtilidades.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADM_Empresa
    {
        public ADM_Empresa()
        {
            this.ADM_Contacto = new HashSet<ADM_Contacto>();
            this.PR_Proyecto = new HashSet<PR_Proyecto>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string PBX { get; set; }
        public string Direccion { get; set; }
        public int CantidadTotalEmpleados { get; set; }
        public int CantidadAdministrativo { get; set; }
        public int CantidadDistribucion { get; set; }
        public int CantidadVentas { get; set; }
        public int CantidadProduccion { get; set; }
        public string OtrosDescripcion { get; set; }
        public Nullable<int> CantidadOtros { get; set; }
        public int GiroId { get; set; }
    
        public virtual ICollection<ADM_Contacto> ADM_Contacto { get; set; }
        public virtual ICollection<PR_Proyecto> PR_Proyecto { get; set; }
    }
}
