//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarcoSoftUtilidades.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GE_MensajeCorreo
    {
        public int Id { get; set; }
        public string Asunto { get; set; }
        public string Mensaje { get; set; }
        public string EsHTML { get; set; }
        public string Para { get; set; }
        public string EsLista { get; set; }
        public Nullable<System.DateTime> FechaEnvio { get; set; }
        public string EstadoEnvio { get; set; }
    }
}
