//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarcoSoftUtilidades.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GE_Persona
    {
        public GE_Persona()
        {
            this.Usuario = new HashSet<Usuario>();
        }
    
        public int Id { get; set; }
        public string PrimerNombre { get; set; }
        public string PrimerApellido { get; set; }
        public string Telefono { get; set; }
        public string Direccion { get; set; }
        public string Correo { get; set; }
        public string Extension { get; set; }
        public string Puesto { get; set; }
        public byte[] FotoPerfil { get; set; }
        public string Celular { get; set; }
        public string SegundoNombre { get; set; }
        public string SegundoApellido { get; set; }
        public string ApellidoCasada { get; set; }
        public string Departamento { get; set; }
    
        public virtual ICollection<Usuario> Usuario { get; set; }
        public virtual ADM_Colaborador ADM_Colaborador { get; set; }
        public virtual ADM_Contacto ADM_Contacto { get; set; }
        public virtual PAR_Participante PAR_Participante { get; set; }
    }
}
