//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarcoSoftUtilidades.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAR_Participante
    {
        public PAR_Participante()
        {
            this.PAR_Participante1 = new HashSet<PAR_Participante>();
        }
    
        public int Id { get; set; }
        public Nullable<int> PaisId { get; set; }
        public Nullable<int> GrupoId { get; set; }
        public Nullable<int> Compa { get; set; }
        public int ProyectoId { get; set; }
    
        public virtual ICollection<PAR_Participante> PAR_Participante1 { get; set; }
        public virtual PAR_Participante PAR_Participante2 { get; set; }
        public virtual GE_Persona GE_Persona { get; set; }
    }
}
