//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarcoSoftUtilidades.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PR_Proyecto
    {
        public PR_Proyecto()
        {
            this.PR_Nutricionista = new HashSet<PR_Nutricionista>();
        }
    
        public int Id { get; set; }
        public int EmpresaId { get; set; }
        public string Estado { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFin { get; set; }
        public int NoSemanas { get; set; }
        public int NoParticipantes { get; set; }
        public int NoEnfermeras { get; set; }
        public int NoFacilitadores { get; set; }
        public int NoAsistentes { get; set; }
        public int NoConsultasNutricionales { get; set; }
        public int FrecuenciaConsultas { get; set; }
        public int FrecuenciaAlertas { get; set; }
        public int FrecuenciaAlertasUnidad { get; set; }
        public int FrecuenciaConsultasUnidad { get; set; }
        public string Color { get; set; }
        public Nullable<bool> CrearUsuarios { get; set; }
        public string LogoURL { get; set; }
        public Nullable<int> AseguradoraId { get; set; }
        public Nullable<decimal> IndiceReclamos { get; set; }
        public Nullable<int> NoParticipantesPorGrupo { get; set; }
        public Nullable<System.DateTime> FechaCorreoInvitacion { get; set; }
        public Nullable<System.DateTime> FechaPrimeraCitaDiagnostico { get; set; }
        public Nullable<bool> CitasProgramadas { get; set; }
        public Nullable<bool> MetasCalculadas { get; set; }
        public Nullable<System.DateTime> FechaInicioConsultas { get; set; }
        public Nullable<System.TimeSpan> HoraInicioConsultas { get; set; }
        public Nullable<System.TimeSpan> HoraFinConsultas { get; set; }
        public Nullable<System.TimeSpan> DuracionConsultas { get; set; }
        public int NoNutricionistas { get; set; }
        public Nullable<int> TipoProyectoId { get; set; }
        public string Nombre { get; set; }
        public string CodigoRegistro { get; set; }
        public string Correo { get; set; }
        public string PasswordCorreo { get; set; }
    
        public virtual ADM_Empresa ADM_Empresa { get; set; }
        public virtual ICollection<PR_Nutricionista> PR_Nutricionista { get; set; }
    }
}
