//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarcoSoftUtilidades.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rol
    {
        public Rol()
        {
            this.Permiso = new HashSet<Permiso>();
            this.UsuarioPorRol = new HashSet<UsuarioPorRol>();
        }
    
        public int IdRol { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public int IdPropietario { get; set; }
        public bool Activo { get; set; }
    
        public virtual ICollection<Permiso> Permiso { get; set; }
        public virtual Propietario Propietario { get; set; }
        public virtual ICollection<UsuarioPorRol> UsuarioPorRol { get; set; }
    }
}
