//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarcoSoftUtilidades.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.UsuarioPorRol = new HashSet<UsuarioPorRol>();
        }
    
        public int IdUsuario { get; set; }
        public string NombreUsuario { get; set; }
        public string Contraseña { get; set; }
        public int IdPersona { get; set; }
        public int IdTipoUsuario { get; set; }
        public bool Activo { get; set; }
    
        public virtual TipoUsuario TipoUsuario { get; set; }
        public virtual ICollection<UsuarioPorRol> UsuarioPorRol { get; set; }
        public virtual GE_Persona GE_Persona { get; set; }
    }
}
